var timezones = [
  {code:"ACDT",title:"Australian Central Daylight Savings Time", offset:"+10:30"},
  {code:"ACST",title:"Australian Central Standard Time", offset:"+09:30"},
  {code:"ACT",title:"Acre Time", offset:"-05"},
 // {code:"ACT",title:"ASEAN Common Time", offset:"+06:30 - UTC+09"},
  {code:"ADT",title:"Atlantic Daylight Time", offset:"-03"},
  {code:"AEDT",title:"Australian Eastern Daylight Savings Time", offset:"+11"},
  {code:"AEST",title:"Australian Eastern Standard Time", offset:"+10"},
  {code:"AFT",title:"Afghanistan Time", offset:"+04:30"},
  {code:"AKDT",title:"Alaska Daylight Time", offset:"-08"},
  {code:"AKST",title:"Alaska Standard Time", offset:"-09"},
  {code:"AMST",title:"Amazon Summer Time (Brazil)[1]", offset:"-03"},
  {code:"AMT",title:"Amazon Time (Brazil)[2]", offset:"-04"},
  {code:"AMT",title:"Armenia Time", offset:"+04"},
  {code:"ART",title:"Argentina Time", offset:"-03"},
  {code:"AST",title:"Arabia Standard Time", offset:"+03"},
  {code:"AST",title:"Atlantic Standard Time", offset:"-04"},
  {code:"AWST",title:"Australian Western Standard Time", offset:"+08"},
  {code:"AZOST",title:"Azores Summer Time", offset:"00"},
  {code:"AZOT",title:"Azores Standard Time", offset:"-01"},
  {code:"AZT",title:"Azerbaijan Time", offset:"+04"},
  {code:"BDT",title:"Brunei Time", offset:"+08"},
  {code:"BIOT",title:"British Indian Ocean Time", offset:"+06"},
  {code:"BIT",title:"Baker Island Time", offset:"-12"},
  {code:"BOT",title:"Bolivia Time", offset:"-04"},
  {code:"BRST",title:"Brasilia Summer Time", offset:"-02"},
  {code:"BRT",title:"Brasilia Time", offset:"-03"},
  {code:"BST",title:"Bangladesh Standard Time", offset:"+06"},
  {code:"BST",title:"Bougainville Standard Time[3]", offset:"+11"},
  {code:"BST",title:"British Summer Time (British Standard Time from Feb 1968 to Oct 1971)", offset:"+01"},
  {code:"BTT",title:"Bhutan Time", offset:"+06"},
  {code:"CAT",title:"Central Africa Time", offset:"+02"},
  {code:"CCT",title:"Cocos Islands Time", offset:"+06:30"},
  {code:"CDT",title:"Central Daylight Time (North America)", offset:"-05"},
  {code:"CDT",title:"Cuba Daylight Time[4]", offset:"-04"},
  {code:"CEST",title:"Central European Summer Time (Cf. HAEC)", offset:"+02"},
  {code:"CET",title:"Central European Time", offset:"+01"},
  {code:"CHADT",title:"Chatham Daylight Time", offset:"+13:45"},
  {code:"CHAST",title:"Chatham Standard Time", offset:"+12:45"},
  {code:"CHOT",title:"Choibalsan Standard Time", offset:"+08"},
  {code:"CHOST",title:"Choibalsan Summer Time", offset:"+09"},
  {code:"CHST",title:"Chamorro Standard Time", offset:"+10"},
  {code:"CHUT",title:"Chuuk Time", offset:"+10"},
  {code:"CIST",title:"Clipperton Island Standard Time", offset:"-08"},
  {code:"CIT",title:"Central Indonesia Time", offset:"+08"},
  {code:"CKT",title:"Cook Island Time", offset:"-10"},
  {code:"CLST",title:"Chile Summer Time", offset:"-03"},
  {code:"CLT",title:"Chile Standard Time", offset:"-04"},
  {code:"COST",title:"Colombia Summer Time", offset:"-04"},
  {code:"COT",title:"Colombia Time", offset:"-05"},
  {code:"CST",title:"Central Standard Time (North America)", offset:"-06"},
  {code:"CST",title:"China Standard Time", offset:"+08"},
  {code:"ACST",title:"Central Standard Time (Australia)", offset:"+09:30"},
  {code:"ACDT",title:"Central Summer Time (Australia)", offset:"+10:30"},
  {code:"CST",title:"Cuba Standard Time", offset:"-05"},
  {code:"CT",title:"China time", offset:"+08"},
  {code:"CVT",title:"Cape Verde Time", offset:"-01"},
  {code:"CWST",title:"Central Western Standard Time (Australia) unofficial", offset:"+08:45"},
  {code:"CXT",title:"Christmas Island Time", offset:"+07"},
  {code:"DAVT",title:"Davis Time", offset:"+07"},
  {code:"DDUT",title:"Dumont d'Urville Time", offset:"+10"},
  {code:"DFT",title:"AIX specific equivalent of Central European Time[5]", offset:"+01"},
  {code:"EASST",title:"Easter Island Summer Time", offset:"-05"},
  {code:"EAST",title:"Easter Island Standard Time", offset:"-06"},
  {code:"EAT",title:"East Africa Time", offset:"+03"},
  {code:"ECT",title:"Eastern Caribbean Time (does not recognise DST)", offset:"-04"},
  {code:"ECT",title:"Ecuador Time", offset:"-05"},
  {code:"EDT",title:"Eastern Daylight Time (North America)", offset:"-04"},
  {code:"AEDT",title:"Eastern Summer Time (Australia)", offset:"+11"},
  {code:"EEST",title:"Eastern European Summer Time", offset:"+03"},
  {code:"EET",title:"Eastern European Time", offset:"+02"},
  {code:"EGST",title:"Eastern Greenland Summer Time", offset:"00"},
  {code:"EGT",title:"Eastern Greenland Time", offset:"-01"},
  {code:"EIT",title:"Eastern Indonesian Time", offset:"+09"},
  {code:"EST",title:"Eastern Standard Time (North America)", offset:"-05"},
  {code:"AEST",title:"Eastern Standard Time (Australia)", offset:"+10"},
  {code:"FET",title:"Further-eastern European Time", offset:"+03"},
  {code:"FJT",title:"Fiji Time", offset:"+12"},
  {code:"FKST",title:"Falkland Islands Summer Time", offset:"-03"},
  {code:"FKT",title:"Falkland Islands Time", offset:"-04"},
  {code:"FNT",title:"Fernando de Noronha Time", offset:"-02"},
  {code:"GALT",title:"Galapagos Time", offset:"-06"},
  {code:"GAMT",title:"Gambier Islands", offset:"-09"},
  {code:"GET",title:"Georgia Standard Time", offset:"+04"},
  {code:"GFT",title:"French Guiana Time", offset:"-03"},
  {code:"GILT",title:"Gilbert Island Time", offset:"+12"},
  {code:"GIT",title:"Gambier Island Time", offset:"-09"},
  {code:"GMT",title:"Greenwich Mean Time", offset:"00"},
  {code:"GST",title:"South Georgia and the South Sandwich Islands", offset:"-02"},
  {code:"GST",title:"Gulf Standard Time", offset:"+04"},
  {code:"GYT",title:"Guyana Time", offset:"-04"},
  {code:"HADT",title:"Hawaii-Aleutian Daylight Time", offset:"-09"},
  {code:"HAEC",title:"Heure Avancée d'Europe Centrale francised name for CEST", offset:"+02"},
  {code:"HAST",title:"Hawaii-Aleutian Standard Time", offset:"-10"},
  {code:"HKT",title:"Hong Kong Time", offset:"+08"},
  {code:"HMT",title:"Heard and McDonald Islands Time", offset:"+05"},
  {code:"HOVST",title:"Khovd Summer Time", offset:"+08"},
  {code:"HOVT",title:"Khovd Standard Time", offset:"+07"},
  {code:"ICT",title:"Indochina Time", offset:"+07"},
  {code:"IDT",title:"Israel Daylight Time", offset:"+03"},
  {code:"IOT",title:"Indian Ocean Time", offset:"+03"},
  {code:"IRDT",title:"Iran Daylight Time", offset:"+04:30"},
  {code:"IRKT",title:"Irkutsk Time", offset:"+08"},
  {code:"IRST",title:"Iran Standard Time", offset:"+03:30"},
  {code:"IST",title:"Indian Standard Time", offset:"+05:30"},
  {code:"IST",title:"Irish Standard Time[6]", offset:"+01"},
  {code:"IST",title:"Israel Standard Time", offset:"+02"},
  {code:"JST",title:"Japan Standard Time", offset:"+09"},
  {code:"KGT",title:"Kyrgyzstan time", offset:"+06"},
  {code:"KOST",title:"Kosrae Time", offset:"+11"},
  {code:"KRAT",title:"Krasnoyarsk Time", offset:"+07"},
  {code:"KST",title:"Korea Standard Time", offset:"+09"},
  {code:"LHST",title:"Lord Howe Standard Time", offset:"+10:30"},
  {code:"LHST",title:"Lord Howe Summer Time", offset:"+11"},
  {code:"LINT",title:"Line Islands Time", offset:"+14"},
  {code:"MAGT",title:"Magadan Time", offset:"+12"},
  {code:"MART",title:"Marquesas Islands Time", offset:"-09:30"},
  {code:"MAWT",title:"Mawson Station Time", offset:"+05"},
  {code:"MDT",title:"Mountain Daylight Time (North America)", offset:"-06"},
  {code:"MET",title:"Middle European Time Same zone as CET", offset:"+01"},
  {code:"MEST",title:"Middle European Summer Time Same zone as CEST", offset:"+02"},
  {code:"MHT",title:"Marshall Islands", offset:"+12"},
  {code:"MIST",title:"Macquarie Island Station Time", offset:"+11"},
  {code:"MIT",title:"Marquesas Islands Time", offset:"-09:30"},
  {code:"MMT",title:"Myanmar Standard Time", offset:"+06:30"},
  {code:"MSK",title:"Moscow Time", offset:"+03"},
  {code:"MST",title:"Malaysia Standard Time", offset:"+08"},
  {code:"MST",title:"Mountain Standard Time (North America)", offset:"-07"},
  {code:"MUT",title:"Mauritius Time", offset:"+04"},
  {code:"MVT",title:"Maldives Time", offset:"+05"},
  {code:"MYT",title:"Malaysia Time", offset:"+08"},
  {code:"NCT",title:"New Caledonia Time", offset:"+11"},
  {code:"NDT",title:"Newfoundland Daylight Time", offset:"-02:30"},
  {code:"NFT",title:"Norfolk Time", offset:"+11"},
  {code:"NPT",title:"Nepal Time", offset:"+05:45"},
  {code:"NST",title:"Newfoundland Standard Time", offset:"-03:30"},
  {code:"NT",title:"Newfoundland Time", offset:"-03:30"},
  {code:"NUT",title:"Niue Time", offset:"-11"},
  {code:"NZDT",title:"New Zealand Daylight Time", offset:"+13"},
  {code:"NZST",title:"New Zealand Standard Time", offset:"+12"},
  {code:"OMST",title:"Omsk Time", offset:"+06"},
  {code:"ORAT",title:"Oral Time", offset:"+05"},
  {code:"PDT",title:"Pacific Daylight Time (North America)", offset:"-07"},
  {code:"PET",title:"Peru Time", offset:"-05"},
  {code:"PETT",title:"Kamchatka Time", offset:"+12"},
  {code:"PGT",title:"Papua New Guinea Time", offset:"+10"},
  {code:"PHOT",title:"Phoenix Island Time", offset:"+13"},
  {code:"PHT",title:"Philippine Time", offset:"+08"},
  {code:"PKT",title:"Pakistan Standard Time", offset:"+05"},
  {code:"PMDT",title:"Saint Pierre and Miquelon Daylight time", offset:"-02"},
  {code:"PMST",title:"Saint Pierre and Miquelon Standard Time", offset:"-03"},
  {code:"PONT",title:"Pohnpei Standard Time", offset:"+11"},
  {code:"PST",title:"Pacific Standard Time (North America)", offset:"-08"},
  {code:"PST",title:"Philippine Standard Time", offset:"+08"},
  {code:"PYST",title:"Paraguay Summer Time (South America)[7]", offset:"-03"},
  {code:"PYT",title:"Paraguay Time (South America)[8]", offset:"-04"},
  {code:"RET",title:"Réunion Time", offset:"+04"},
  {code:"ROTT",title:"Rothera Research Station Time", offset:"-03"},
  {code:"SAKT",title:"Sakhalin Island time", offset:"+11"},
  {code:"SAMT",title:"Samara Time", offset:"+04"},
  {code:"SAST",title:"South African Standard Time", offset:"+02"},
  {code:"SBT",title:"Solomon Islands Time", offset:"+11"},
  {code:"SCT",title:"Seychelles Time", offset:"+04"},
  {code:"SGT",title:"Singapore Time", offset:"+08"},
  {code:"SLST",title:"Sri Lanka Standard Time", offset:"+05:30"},
  {code:"SRET",title:"Srednekolymsk Time", offset:"+11"},
  {code:"SRT",title:"Suriname Time", offset:"-03"},
  {code:"SST",title:"Samoa Standard Time", offset:"-11"},
  {code:"SST",title:"Singapore Standard Time", offset:"+08"},
  {code:"SYOT",title:"Showa Station Time", offset:"+03"},
  {code:"TAHT",title:"Tahiti Time", offset:"-10"},
  {code:"THA",title:"Thailand Standard Time", offset:"+07"},
  {code:"TFT",title:"Indian/Kerguelen", offset:"+05"},
  {code:"TJT",title:"Tajikistan Time", offset:"+05"},
  {code:"TKT",title:"Tokelau Time", offset:"+13"},
  {code:"TLT",title:"Timor Leste Time", offset:"+09"},
  {code:"TMT",title:"Turkmenistan Time", offset:"+05"},
  {code:"TRT",title:"Turkey Time", offset:"+03"},
  {code:"TOT",title:"Tonga Time", offset:"+13"},
  {code:"TVT",title:"Tuvalu Time", offset:"+12"},
  {code:"ULAST",title:"Ulaanbaatar Summer Time", offset:"+09"},
  {code:"ULAT",title:"Ulaanbaatar Standard Time", offset:"+08"},
  {code:"USZ1",title:"Kaliningrad Time", offset:"+02"},
  {code:"UTC",title:"Coordinated Universal Time", offset:"00"},
  {code:"UYST",title:"Uruguay Summer Time", offset:"-02"},
  {code:"UYT",title:"Uruguay Standard Time", offset:"-03"},
  {code:"UZT",title:"Uzbekistan Time", offset:"+05"},
  {code:"VET",title:"Venezuelan Standard Time", offset:"-04"},
  {code:"VLAT",title:"Vladivostok Time", offset:"+10"},
  {code:"VOLT",title:"Volgograd Time", offset:"+04"},
  {code:"VOST",title:"Vostok Station Time", offset:"+06"},
  {code:"VUT",title:"Vanuatu Time", offset:"+11"},
  {code:"WAKT",title:"Wake Island Time", offset:"+12"},
  {code:"WAST",title:"West Africa Summer Time", offset:"+02"},
  {code:"WAT",title:"West Africa Time", offset:"+01"},
  {code:"WEST",title:"Western European Summer Time", offset:"+01"},
  {code:"WET",title:"Western European Time", offset:"00"},
  {code:"WIT",title:"Western Indonesian Time", offset:"+07"},
  {code:"WST",title:"Western Standard Time", offset:"+08"},
  {code:"YAKT",title:"Yakutsk Time", offset:"+09"},
  {code:"YEKT",title:"Yekaterinburg Time", offset:"+05"},
];

module.exports = timezones;